[ja]
title = "UmentuLab Techblog"
description = ""
weight = 1
LanguageName = "JA"
contentDir = "content/ja"

[en]
title = "UmentuLab Techblog"
description = ""
contentDir = "content/en" 
weight = 1
LanguageName = "EN"
