# 公開するページのURL
baseURL = "https://weblog.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "UmentuLab TechBlog"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Umentu Lab(Shintaro Tachibana)"
    bio = "SREとか機械学習とかやってる人"
    avatar = "img/avatar.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Umentu Lab(Shintaro Tachibana)"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "umekichinano"
  github = "umentu"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

